rails_url_help: "https://www.railstutorial.org/help"
github_url: "https://github.com/khanhdx-0573/sample_app"
rails_tutorial_url: "https://www.railstutorial.org/"
app_name: "Sample App"
max_name_length: 50
max_email_length: 255
min_password_length: 6
valid_email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
